.TH "Catch::TagAlias" 3 "Mon Jun 19 2017" "TP1 Projeto 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::TagAlias
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTagAlias\fP (std::string const &_tag, \fBSourceLineInfo\fP _lineInfo)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBtag\fP"
.br
.ti -1c
.RI "\fBSourceLineInfo\fP \fBlineInfo\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::TagAlias::TagAlias (std::string const & _tag, \fBSourceLineInfo\fP _lineInfo)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBSourceLineInfo\fP Catch::TagAlias::lineInfo"

.SS "std::string Catch::TagAlias::tag"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP1 Projeto 2 from the source code\&.
