.TH "Catch::Matchers::Vector::ContainsMatcher< T >" 3 "Mon Jun 19 2017" "TP1 Projeto 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::Vector::ContainsMatcher< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.PP
Inherits \fBCatch::Matchers::Impl::MatcherBase< ObjectT, ComparatorT >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContainsMatcher\fP (std::vector< T > const &comparator)"
.br
.ti -1c
.RI "bool \fBmatch\fP (std::vector< T > const &v) const \fBCATCH_OVERRIDE\fP"
.br
.ti -1c
.RI "virtual std::string \fBdescribe\fP () const \fBCATCH_OVERRIDE\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< T > const  & \fBm_comparator\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBCatch::Matchers::Vector::ContainsMatcher\fP< T >::\fBContainsMatcher\fP (std::vector< T > const & comparator)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > virtual std::string \fBCatch::Matchers::Vector::ContainsMatcher\fP< T >::describe () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBCatch::Matchers::Impl::MatcherUntypedBase\fP\&.
.SS "template<typename T > bool \fBCatch::Matchers::Vector::ContainsMatcher\fP< T >::match (std::vector< T > const & v) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename T > std::vector<T> const& \fBCatch::Matchers::Vector::ContainsMatcher\fP< T >::m_comparator"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP1 Projeto 2 from the source code\&.
