.TH "Catch::Matchers::StdString::CasedString" 3 "Mon Jun 19 2017" "TP1 Projeto 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::StdString::CasedString
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCasedString\fP (std::string const &str, \fBCaseSensitive::Choice\fP caseSensitivity)"
.br
.ti -1c
.RI "std::string \fBadjustString\fP (std::string const &str) const"
.br
.ti -1c
.RI "std::string \fBcaseSensitivitySuffix\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCaseSensitive::Choice\fP \fBm_caseSensitivity\fP"
.br
.ti -1c
.RI "std::string \fBm_str\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::Matchers::StdString::CasedString::CasedString (std::string const & str, \fBCaseSensitive::Choice\fP caseSensitivity)"

.SH "Member Function Documentation"
.PP 
.SS "std::string Catch::Matchers::StdString::CasedString::adjustString (std::string const & str) const"

.SS "std::string Catch::Matchers::StdString::CasedString::caseSensitivitySuffix () const"

.SH "Member Data Documentation"
.PP 
.SS "\fBCaseSensitive::Choice\fP Catch::Matchers::StdString::CasedString::m_caseSensitivity"

.SS "std::string Catch::Matchers::StdString::CasedString::m_str"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP1 Projeto 2 from the source code\&.
