.TH "Catch::Matchers::StdString::StringMatcherBase" 3 "Mon Jun 19 2017" "TP1 Projeto 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Matchers::StdString::StringMatcherBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.PP
Inherits \fBCatch::Matchers::Impl::MatcherBase< ObjectT, ComparatorT >\fP\&.
.PP
Inherited by \fBCatch::Matchers::StdString::ContainsMatcher\fP, \fBCatch::Matchers::StdString::EndsWithMatcher\fP, \fBCatch::Matchers::StdString::EqualsMatcher\fP, and \fBCatch::Matchers::StdString::StartsWithMatcher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStringMatcherBase\fP (std::string const &operation, \fBCasedString\fP const &comparator)"
.br
.ti -1c
.RI "virtual std::string \fBdescribe\fP () const \fBCATCH_OVERRIDE\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCasedString\fP \fBm_comparator\fP"
.br
.ti -1c
.RI "std::string \fBm_operation\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::Matchers::StdString::StringMatcherBase::StringMatcherBase (std::string const & operation, \fBCasedString\fP const & comparator)"

.SH "Member Function Documentation"
.PP 
.SS "virtual std::string Catch::Matchers::StdString::StringMatcherBase::describe () const\fC [virtual]\fP"

.PP
Implements \fBCatch::Matchers::Impl::MatcherUntypedBase\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCasedString\fP Catch::Matchers::StdString::StringMatcherBase::m_comparator"

.SS "std::string Catch::Matchers::StdString::StringMatcherBase::m_operation"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP1 Projeto 2 from the source code\&.
