.TH "Catch::pluralise" 3 "Mon Jun 19 2017" "TP1 Projeto 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::pluralise
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpluralise\fP (std::size_t count, std::string const &label)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::size_t \fBm_count\fP"
.br
.ti -1c
.RI "std::string \fBm_label\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, \fBpluralise\fP const &pluraliser)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::pluralise::pluralise (std::size_t count, std::string const & label)"

.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & os, \fBpluralise\fP const & pluraliser)\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::size_t Catch::pluralise::m_count"

.SS "std::string Catch::pluralise::m_label"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP1 Projeto 2 from the source code\&.
