.TH "Catch::AssertionInfo" 3 "Mon Jun 19 2017" "TP1 Projeto 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::AssertionInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssertionInfo\fP ()"
.br
.ti -1c
.RI "\fBAssertionInfo\fP (std::string const &_macroName, \fBSourceLineInfo\fP const &_lineInfo, std::string const &_capturedExpression, \fBResultDisposition::Flags\fP _resultDisposition)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBmacroName\fP"
.br
.ti -1c
.RI "\fBSourceLineInfo\fP \fBlineInfo\fP"
.br
.ti -1c
.RI "std::string \fBcapturedExpression\fP"
.br
.ti -1c
.RI "\fBResultDisposition::Flags\fP \fBresultDisposition\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::AssertionInfo::AssertionInfo ()\fC [inline]\fP"

.SS "Catch::AssertionInfo::AssertionInfo (std::string const & _macroName, \fBSourceLineInfo\fP const & _lineInfo, std::string const & _capturedExpression, \fBResultDisposition::Flags\fP _resultDisposition)"

.SH "Member Data Documentation"
.PP 
.SS "std::string Catch::AssertionInfo::capturedExpression"

.SS "\fBSourceLineInfo\fP Catch::AssertionInfo::lineInfo"

.SS "std::string Catch::AssertionInfo::macroName"

.SS "\fBResultDisposition::Flags\fP Catch::AssertionInfo::resultDisposition"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP1 Projeto 2 from the source code\&.
