.TH "Catch::CopyableStream" 3 "Mon Jun 19 2017" "TP1 Projeto 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::CopyableStream
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCopyableStream\fP ()"
.br
.ti -1c
.RI "\fBCopyableStream\fP (\fBCopyableStream\fP const &other)"
.br
.ti -1c
.RI "\fBCopyableStream\fP & \fBoperator=\fP (\fBCopyableStream\fP const &other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::ostringstream \fBoss\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::CopyableStream::CopyableStream ()\fC [inline]\fP"

.SS "Catch::CopyableStream::CopyableStream (\fBCopyableStream\fP const & other)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBCopyableStream\fP& Catch::CopyableStream::operator= (\fBCopyableStream\fP const & other)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::ostringstream Catch::CopyableStream::oss"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP1 Projeto 2 from the source code\&.
