.TH "Catch::MessageBuilder" 3 "Mon Jun 19 2017" "TP1 Projeto 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::MessageBuilder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessageBuilder\fP (std::string const &macroName, \fBSourceLineInfo\fP const &lineInfo, \fBResultWas::OfType\fP type)"
.br
.ti -1c
.RI "template<typename T > \fBMessageBuilder\fP & \fBoperator<<\fP (T const &value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMessageInfo\fP \fBm_info\fP"
.br
.ti -1c
.RI "std::ostringstream \fBm_stream\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::MessageBuilder::MessageBuilder (std::string const & macroName, \fBSourceLineInfo\fP const & lineInfo, \fBResultWas::OfType\fP type)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > \fBMessageBuilder\fP& Catch::MessageBuilder::operator<< (T const & value)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBMessageInfo\fP Catch::MessageBuilder::m_info"

.SS "std::ostringstream Catch::MessageBuilder::m_stream"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP1 Projeto 2 from the source code\&.
