.TH "Catch::StringMaker< T * >" 3 "Mon Jun 19 2017" "TP1 Projeto 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::StringMaker< T * >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename U > static std::string \fBconvert\fP (U *p)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > template<typename U > static std::string \fBCatch::StringMaker\fP< T * >::convert (U * p)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP1 Projeto 2 from the source code\&.
