.TH "Catch::Detail" 3 "Mon Jun 19 2017" "TP1 Projeto 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::Detail
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApprox\fP"
.br
.ti -1c
.RI "struct \fBBorgType\fP"
.br
.ti -1c
.RI "struct \fBFalseType\fP"
.br
.ti -1c
.RI "struct \fBIsStreamInsertable\fP"
.br
.ti -1c
.RI "struct \fBStringMakerBase\fP"
.br
.ti -1c
.RI "struct \fBStringMakerBase< true >\fP"
.br
.ti -1c
.RI "struct \fBTrueType\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTrueType\fP & \fBtestStreamable\fP (std::ostream &)"
.br
.ti -1c
.RI "\fBFalseType\fP \fBtestStreamable\fP (\fBFalseType\fP)"
.br
.ti -1c
.RI "\fBFalseType\fP \fBoperator<<\fP (std::ostream const &, \fBBorgType\fP const &)"
.br
.ti -1c
.RI "std::string \fBrawMemoryToString\fP (const void *object, std::size_t size)"
.br
.ti -1c
.RI "template<typename T > std::string \fBrawMemoryToString\fP (const T &object)"
.br
.ti -1c
.RI "template<typename InputIterator > std::string \fBrangeToString\fP (InputIterator first, InputIterator last)"
.br
.ti -1c
.RI "template<typename T > std::string \fBmakeString\fP (T const &value)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBunprintableString\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T > std::string Catch::Detail::makeString (T const & value)"

.SS "\fBFalseType\fP Catch::Detail::operator<< (std::ostream const &, \fBBorgType\fP const &)"

.SS "template<typename InputIterator > std::string Catch::Detail::rangeToString (InputIterator first, InputIterator last)"

.SS "std::string Catch::Detail::rawMemoryToString (const void * object, std::size_t size)"

.SS "template<typename T > std::string Catch::Detail::rawMemoryToString (const T & object)\fC [inline]\fP"

.SS "\fBTrueType\fP& Catch::Detail::testStreamable (std::ostream &)"

.SS "\fBFalseType\fP Catch::Detail::testStreamable (\fBFalseType\fP)"

.SH "Variable Documentation"
.PP 
.SS "const std::string Catch::Detail::unprintableString"

.SH "Author"
.PP 
Generated automatically by Doxygen for TP1 Projeto 2 from the source code\&.
