.TH "Catch::AssertionResultData" 3 "Mon Jun 19 2017" "TP1 Projeto 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::AssertionResultData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssertionResultData\fP ()"
.br
.ti -1c
.RI "void \fBnegate\fP (bool parenthesize)"
.br
.ti -1c
.RI "std::string const  & \fBreconstructExpression\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDecomposedExpression\fP const  * \fBdecomposedExpression\fP"
.br
.ti -1c
.RI "std::string \fBreconstructedExpression\fP"
.br
.ti -1c
.RI "std::string \fBmessage\fP"
.br
.ti -1c
.RI "\fBResultWas::OfType\fP \fBresultType\fP"
.br
.ti -1c
.RI "bool \fBnegated\fP"
.br
.ti -1c
.RI "bool \fBparenthesized\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Catch::AssertionResultData::AssertionResultData ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Catch::AssertionResultData::negate (bool parenthesize)\fC [inline]\fP"

.SS "std::string const& Catch::AssertionResultData::reconstructExpression () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBDecomposedExpression\fP const* Catch::AssertionResultData::decomposedExpression\fC [mutable]\fP"

.SS "std::string Catch::AssertionResultData::message"

.SS "bool Catch::AssertionResultData::negated"

.SS "bool Catch::AssertionResultData::parenthesized"

.SS "std::string Catch::AssertionResultData::reconstructedExpression\fC [mutable]\fP"

.SS "\fBResultWas::OfType\fP Catch::AssertionResultData::resultType"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP1 Projeto 2 from the source code\&.
