.TH "Catch::StreamEndStop" 3 "Mon Jun 19 2017" "TP1 Projeto 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::StreamEndStop
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBoperator+\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::string Catch::StreamEndStop::operator+ ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP1 Projeto 2 from the source code\&.
