.TH "Catch::ExceptionTranslatorRegistrar" 3 "Mon Jun 19 2017" "TP1 Projeto 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catch::ExceptionTranslatorRegistrar
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <catch\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > \fBExceptionTranslatorRegistrar\fP (std::string(*translateFunction)(T &))"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > Catch::ExceptionTranslatorRegistrar::ExceptionTranslatorRegistrar (std::string(*)(T &) translateFunction)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP1 Projeto 2 from the source code\&.
