.TH "funcoes.cpp" 3 "Mon Jun 19 2017" "TP1 Projeto 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
funcoes.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpermitirAcesso\fP (int escolhido, bool autenticado)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int permitirAcesso (int escolhido, bool autenticado)"

.SH "Author"
.PP 
Generated automatically by Doxygen for TP1 Projeto 2 from the source code\&.
