.TH "Gerenciador" 3 "Sun Jul 2 2017" "Projeto TP1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Gerenciador \- \fBGerenciador\fP de acesso ao Laboratório\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGerenciador\fP ()"
.br
.ti -1c
.RI "int \fBpermitirAcesso\fP (\fBUsuario\fP &usuario, \fBSala\fP &salaDesejada, int sala, int horarioDesejado)"
.br
.RI "Permite acesso às salas e ao laboratório 0: \fBSala\fP 1 1: \fBSala\fP 2 2: \fBSala\fP 3\&. "
.ti -1c
.RI "\fBGerenciador\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGerenciador\fP de acesso ao Laboratório\&. 

Ele será o responsável por receber as informações do usuário para liberar entrada ao laboratório\&. TODO: Concluir\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Gerenciador::Gerenciador ()\fC [inline]\fP"

.SS "Gerenciador::Gerenciador ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int Gerenciador::permitirAcesso (\fBUsuario\fP & usuario, \fBSala\fP & salaDesejada, int sala, int horarioDesejado)\fC [inline]\fP"

.PP
Permite acesso às salas e ao laboratório 0: \fBSala\fP 1 1: \fBSala\fP 2 2: \fBSala\fP 3\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Projeto TP1 from the source code\&.
