.TH "resumo.cpp" 3 "Sun Jul 2 2017" "Projeto TP1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
resumo.cpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAutenticador\fP"
.br
.RI "Classe responsável por autenticar reservas de salas e possíveis erros com a identificação facial\&. "
.ti -1c
.RI "class \fBEvento\fP"
.br
.RI "Classe responsável por conter todos os eventos de um dia de uma sala\&. "
.ti -1c
.RI "class \fBDia\fP"
.br
.ti -1c
.RI "class \fBSemana\fP"
.br
.ti -1c
.RI "class \fBSala\fP"
.br
.ti -1c
.RI "class \fBUsuario\fP"
.br
.RI "Classe principal, comunica com gerenciador e autenticador\&. "
.ti -1c
.RI "class \fBGerenciador\fP"
.br
.RI "\fBGerenciador\fP de acesso ao Laboratório\&. "
.ti -1c
.RI "class \fBLaboratorio\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Projeto TP1 from the source code\&.
