.TH "test.cpp" 3 "Mon Jun 19 2017" "TP1 Projeto 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'others/catch\&.hpp'\fP
.br
\fC#include 'funcoes\&.cpp'\fP
.br
\fC#include 'classes\&.cpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCATCH_CONFIG_MAIN\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_CASE\fP ('Verificação de interface de linha de comando')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('Verificação de classes')"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CATCH_CONFIG_MAIN"

.SH "Function Documentation"
.PP 
.SS "TEST_CASE ('Verificação de interface de linha de comando')"

.SS "TEST_CASE ('Verificação de classes')"

.SH "Author"
.PP 
Generated automatically by Doxygen for TP1 Projeto 2 from the source code\&.
