.TH "Usuario" 3 "Mon Jun 19 2017" "TP1 Projeto 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Usuario
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUsuario\fP ()"
.br
.ti -1c
.RI "\fBUsuario\fP (std::string novoNome, std::string novoSobrenome, std::string novoCPFouMatricula, int novoId)"
.br
.ti -1c
.RI "std::string \fBgetNome\fP (void)"
.br
.ti -1c
.RI "std::string \fBgetSobrenome\fP (void)"
.br
.ti -1c
.RI "std::string \fBgetCPFouMatricula\fP ()"
.br
.ti -1c
.RI "int \fBgetId\fP (void)"
.br
.ti -1c
.RI "std::string \fBpedirReserva\fP (\fBAutenticador\fP &autenticador, std::string token)"
.br
.ti -1c
.RI "std::string \fBrequisitarAcesso\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Usuario::Usuario ()\fC [inline]\fP"

.SS "Usuario::Usuario (std::string novoNome, std::string novoSobrenome, std::string novoCPFouMatricula, int novoId)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string Usuario::getCPFouMatricula ()\fC [inline]\fP"

.SS "int Usuario::getId (void)\fC [inline]\fP"

.SS "std::string Usuario::getNome (void)\fC [inline]\fP"

.SS "std::string Usuario::getSobrenome (void)\fC [inline]\fP"

.SS "std::string Usuario::pedirReserva (\fBAutenticador\fP & autenticador, std::string token)\fC [inline]\fP"

.SS "std::string Usuario::requisitarAcesso ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TP1 Projeto 2 from the source code\&.
