.TH "classes.cpp" 3 "Mon Jun 26 2017" "Projeto Laboratório TP1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
classes.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAutenticador\fP"
.br
.RI "Classe responsável por autenticar reservas de salas e possíveis erros com a identificação facial\&. "
.ti -1c
.RI "class \fBUsuario\fP"
.br
.RI "Classe principal, comunica com gerenciador e autenticador Tipos de usuários -1: não cadastrado 0: genérico (somente pode entrar no laboratório) 1: aluno (não pode reservar, pode entrar somente nas salas designadas) 2: palestrante (pode reservar somente eventos únicos, pode entrar somente nas salas designadas) 3: professor (pode reservar qualquer evento, pode entrar somente nas salas designadas) 4: funcionario (pode reservar qualquer evento, pode entrar em tudo) "
.ti -1c
.RI "class \fBEvento\fP"
.br
.RI "Classe responsável por conter todos os eventos do laboratório\&. "
.ti -1c
.RI "class \fBDia\fP"
.br
.ti -1c
.RI "class \fBSemana\fP"
.br
.ti -1c
.RI "class \fBSala\fP"
.br
.ti -1c
.RI "class \fBGerenciador\fP"
.br
.RI "\fBGerenciador\fP de acesso ao Laboratório\&. "
.ti -1c
.RI "class \fBLaboratorio\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Projeto Laboratório TP1 from the source code\&.
