.TH "Dia" 3 "Mon Jun 26 2017" "Projeto Laboratório TP1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dia
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDia\fP ()"
.br
.ti -1c
.RI "\fBDia\fP (std::string nomeDia)"
.br
.ti -1c
.RI "std::string \fBmudaEvento\fP (\fBAutenticador\fP &autenticador, std::string token, \fBEvento\fP novoEvento, int horario)"
.br
.ti -1c
.RI "std::string \fBmostraEvento\fP (int horario)"
.br
.ti -1c
.RI "std::string \fBmostraNomeDia\fP ()"
.br
.ti -1c
.RI "std::string \fBverificaParticipante\fP (std::string participanteVerificado, int horarioDesejado)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBnome\fP"
.br
.ti -1c
.RI "\fBEvento\fP \fBeventos\fP [12]"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Dia::Dia ()\fC [inline]\fP"

.SS "Dia::Dia (std::string nomeDia)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string Dia::mostraEvento (int horario)\fC [inline]\fP"

.SS "std::string Dia::mostraNomeDia ()\fC [inline]\fP"

.SS "std::string Dia::mudaEvento (\fBAutenticador\fP & autenticador, std::string token, \fBEvento\fP novoEvento, int horario)\fC [inline]\fP"

.SS "std::string Dia::verificaParticipante (std::string participanteVerificado, int horarioDesejado)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBEvento\fP Dia::eventos[12]"

.SS "std::string Dia::nome"


.SH "Author"
.PP 
Generated automatically by Doxygen for Projeto Laboratório TP1 from the source code\&.
