.TH "jsontest.cpp" 3 "Mon Jun 26 2017" "Projeto Laboratório TP1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsontest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'others/json\&.hpp'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBjson\fP = nlohmann::json"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBjson\fP =  nlohmann::json"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Projeto Laboratório TP1 from the source code\&.
