.TH "test.cpp" 3 "Mon Jun 26 2017" "Projeto Laboratório TP1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'others/catch\&.hpp'\fP
.br
\fC#include 'funcoes\&.cpp'\fP
.br
\fC#include 'classes\&.cpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCATCH_CONFIG_MAIN\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_CASE\fP ('Verificação de classes')"
.br
.RI "Unit Tests\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CATCH_CONFIG_MAIN"

.SH "Function Documentation"
.PP 
.SS "TEST_CASE ('Verificação de classes')"

.PP
Unit Tests\&. 
.IP "1." 4
Criar teste;
.IP "2." 4
Teste falhar;
.IP "3." 4
Implementar código (mantém-se no 3 enquanto 4 não ocorrer);
.IP "4." 4
Teste bem sucedido;
.IP "5." 4
Voltar ao passo (1) até conclusão do projeto\&.
.PP
.PP
Estrutura dos testes é a seguinte:
.IP "1." 4
Inicializa testes com TEST_CASE;
.IP "2." 4
Inicializa objetos para teste
.IP "3." 4
Verifica funções de classes, separando diferentes classes com SECTION
.IP "4." 4
No início e no final do teste de uma classe, imprime na linha de comando qual classe está sendo testada\&. 
.PP
\fBLaboratorio\fP possui 2 eventos
.SH "Author"
.PP 
Generated automatically by Doxygen for Projeto Laboratório TP1 from the source code\&.
