.TH "Usuario" 3 "Mon Jun 26 2017" "Projeto Laboratório TP1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Usuario \- Classe principal, comunica com gerenciador e autenticador Tipos de usuários -1: não cadastrado 0: genérico (somente pode entrar no laboratório) 1: aluno (não pode reservar, pode entrar somente nas salas designadas) 2: palestrante (pode reservar somente eventos únicos, pode entrar somente nas salas designadas) 3: professor (pode reservar qualquer evento, pode entrar somente nas salas designadas) 4: funcionario (pode reservar qualquer evento, pode entrar em tudo)  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUsuario\fP ()"
.br
.ti -1c
.RI "\fBUsuario\fP (std::string novoNome, std::string novoSobrenome, std::string novoCPF, int novoTipo)"
.br
.ti -1c
.RI "std::string \fBgetNome\fP (void)"
.br
.ti -1c
.RI "std::string \fBgetSobrenome\fP (void)"
.br
.ti -1c
.RI "std::string \fBgetCPF\fP (void)"
.br
.ti -1c
.RI "int \fBgetId\fP (void)"
.br
.ti -1c
.RI "std::string \fBpedirReserva\fP (\fBAutenticador\fP &autenticador, \fBEvento\fP &eventoNovo, int horarioDesejado)"
.br
.RI "Função responsável pela reserva de salas para eventos\&. "
.ti -1c
.RI "int \fBrequisitarAcesso\fP (\fBLaboratorio\fP &laboratorio, int salaDesejada, int horarioDesejado)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classe principal, comunica com gerenciador e autenticador Tipos de usuários -1: não cadastrado 0: genérico (somente pode entrar no laboratório) 1: aluno (não pode reservar, pode entrar somente nas salas designadas) 2: palestrante (pode reservar somente eventos únicos, pode entrar somente nas salas designadas) 3: professor (pode reservar qualquer evento, pode entrar somente nas salas designadas) 4: funcionario (pode reservar qualquer evento, pode entrar em tudo) 

TODO: Concluir\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Usuario::Usuario ()\fC [inline]\fP"

.SS "Usuario::Usuario (std::string novoNome, std::string novoSobrenome, std::string novoCPF, int novoTipo)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string Usuario::getCPF (void)\fC [inline]\fP"

.SS "int Usuario::getId (void)\fC [inline]\fP"

.SS "std::string Usuario::getNome (void)\fC [inline]\fP"

.SS "std::string Usuario::getSobrenome (void)\fC [inline]\fP"

.SS "std::string Usuario::pedirReserva (\fBAutenticador\fP & autenticador, \fBEvento\fP & eventoNovo, int horarioDesejado)\fC [inline]\fP"

.PP
Função responsável pela reserva de salas para eventos\&. FIXME: Melhorar função 
.SS "int Usuario::requisitarAcesso (\fBLaboratorio\fP & laboratorio, int salaDesejada, int horarioDesejado)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Projeto Laboratório TP1 from the source code\&.
